server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:gme.db
  application:
    name: graph_memory_engine

logging:
  level:
    com:
      gme: DEBUG

llm:
  api:
    url: http://localhost:11434/v1/chat/completions
    key: dummy key


